version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: window-explorer-postgres
    environment:
      POSTGRES_USER: window_explorer
      POSTGRES_PASSWORD: window_explorer123
      POSTGRES_DB: window_explorer_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U window_explorer']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - window-explorer-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: window-explorer-redis
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - window-explorer-network

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: window-explorer-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: window_explorer
      RABBITMQ_DEFAULT_PASS: window_explorer123
    ports:
      - '5672:5672' # AMQP
      - '15672:15672' # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - window-explorer-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  window-explorer-network:
    driver: bridge
