services:
  postgres:
    image: postgres:16-alpine
    container_name: window-explorer-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: window-explorer
      POSTGRES_PASSWORD: window-explorer_password
      POSTGRES_DB: window-explorer_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U window-explorer']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: window-explorer-redis-dev
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: window-explorer-rabbitmq-dev
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: window-explorer
      RABBITMQ_DEFAULT_PASS: window-explorer_password
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_dev_data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_dev_data:
  redis_dev_data:
  rabbitmq_dev_data:
