name: Deploy to Ubuntu Server

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            # Jangan pakai -u agar tidak error unbound variable
            set -Eeo pipefail

            # ===============================
            # Inject variabel dari GitHub Secrets
            # Pastikan sudah dibuat di repo: APP_DIR, DB_SERVICE, DB_URL
            # ===============================
            APP_DIR="${{ secrets.APP_DIR }}"
            DB_SERVICE="${{ secrets.DB_SERVICE }}"
            DB_URL="${{ secrets.DB_URL }}"

            # Validasi sekilas
            [ -n "$APP_DIR" ] || { echo "APP_DIR secret is empty"; exit 1; }
            [ -n "$DB_SERVICE" ] || { echo "DB_SERVICE secret is empty"; exit 1; }
            [ -n "$DB_URL" ] || { echo "DB_URL secret is empty"; exit 1; }

            echo "→ Switching to ${APP_DIR}"
            cd "$APP_DIR"

            echo "→ Ensure bun in PATH"
            export PATH="$HOME/.bun/bin:$PATH"

            echo "→ Fetching latest code"
            if [ -d .git ]; then
              git fetch origin master
              git reset --hard origin/master
            else
              echo "Repository not initialized at ${APP_DIR}"
              exit 1
            fi

            echo "→ Installing dependencies (host)"
            bun install

            # ====== Infrastructure via Docker Compose ======
            COMPOSE_FILE="docker-compose.prod.yml"
            echo "→ Starting infrastructure: ${COMPOSE_FILE}"
            sudo docker compose -f "$COMPOSE_FILE" up -d

            echo "→ Waiting containers to settle..."
            sleep 10
            sudo docker compose -f "$COMPOSE_FILE" ps

            echo "→ Waiting for PostgreSQL to be ready..."
            max_attempts=30
            attempt=1
            until sudo
